<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$protocol = 'http';
if (in_array($_SERVER['HTTP_HOST'], ['innovativefinancinglab.com','www.innovativefinancinglab.com'])) {
    $protocol = 'https';
}
$root = $protocol."://".$_SERVER['HTTP_HOST'];
$root .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
 
$config['base_url']    = $root;


/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';
$config['lang']	= '';
if(!empty($_COOKIE['lang'])) {
    $config['lang']	= $_COOKIE['lang'];
}

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

/* custom */
$config['question'] = [
    [
        'id'=>1,
        'title'=>'Apakah ada masalah khusus yang dihadapi oleh kota tempat kamu tinggal?',
        'titleen'=>'Are there any specific issues that impacted the city where you reside?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'tingginya tingkat polusi udara',
                'titleen'=>'high level of air pollution'
            ],
            [
                'id'=>'b',
                'title'=>'pandemi COVID-19',
                'titleen'=>'COVID-19 pandemic'
            ],
            [
                'id'=>'c',
                'title'=>'banjir, gempa bumi dan bencana alam lainnya',
                'titleen'=>'flooding, earthquakes or other natural hazards'
            ],
            [
                'id'=>'d',
                'title'=>'kesenjangan sosial dan ekonomi yang tinggi',
                'titleen'=>'high level of socioeconomic inequality'
            ],
            [
                'id'=>'e',
                'title'=>'isu penanganan sampah dan limbah',
                'titleen'=>'waste management issues'
            ],
            [
                'id'=>'f',
                'title'=>'lainnya',
                'titleen'=>'others'
            ],
        ]
    ],
    [
        'id'=>2,
        'title'=>'Bagaimana perasaan kamu terhadap tantangan-tantangan tersebut?',
        'titleen'=>'How do you feel about these challenges?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'Isunya tidak penting',
                'titleen'=>'The issue is not important'
            ],
            [
                'id'=>'b',
                'title'=>'Aku tidak mau tahu',
                'titleen'=>'I prefer not knowing'
            ],
            [
                'id'=>'c',
                'title'=>'Prihatin, tapi bingung cara membantu',
                'titleen'=>'I empathized, but unsure on how to help'
            ],
            [
                'id'=>'d',
                'title'=>'Isunya tidak mempengaruhi diriku',
                'titleen'=>"The issue doesn't concern my own condition"
            ],
            [
                'id'=>'e',
                'title'=>'Prihatin dan sudah beraksi membantu',
                'titleen'=>'I empathized and have acted on it'
            ],
        ]
    ],
    [
        'id'=>3,
        'title'=>'Coba perhatikan, adakah hal yang berubah dalam <span class="bg-t-blue text-white">lingkungan alam</span> di sekitar kita?',
        'titleen'=>'Has there been anything that changed regarding the <span class="bg-t-blue text-white">environment</span>?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'cuaca tidak menentu dan seringnya bencana',
                'titleen'=>'extreme weather and frequent disasters'
            ],
            [
                'id'=>'b',
                'title'=>'berkurangnya penggunaan kendaraan dan polusi udara',
                'titleen'=>'reduced emission and lower levels of air pollution'
            ],
            [
                'id'=>'c',
                'title'=>'tata ruang kota menjadi lebih baik',
                'titleen'=>'improved city planning'
            ],
            [
                'id'=>'d',
                'title'=>'wilayah pesisir kota terendam karena penurunan tanah',
                'titleen'=>"coastal cities are sinking due to land subsidence"
            ],
            [
                'id'=>'e',
                'title'=>'anak muda makin aktif melindungi lingkungan',
                'titleen'=>'increased interest from youth on conservation'
            ],
            [
                'id'=>'f',
                'title'=>'pengurangan penggunaan plastik sekali pakai',
                'titleen'=>'reduced usage of single-use plastic'
            ],
            [
                'id'=>'g',
                'title'=>'peningkatan suhu bumi',
                'titleen'=>"earth's temperature increase"
            ],
            [
                'id'=>'h',
                'title'=>'sulitnya akses air bersih',
                'titleen'=>'limited access to clean water'
            ],
            [
                'id'=>'i',
                'title'=>'penggunaan sumber energi baru dan terbarukan',
                'titleen'=>'usage of renewable energy sources'
            ],
            [
                'id'=>'j',
                'title'=>'lainnya',
                'titleen'=>'others'
            ],
        ]
    ],
    [
        'id'=>4,
        'title'=>'Perhatikan perkembangan <span class="bg-t-blue text-white">teknologi</span><br>Adakah yang berubah?',
        'titleen'=>'Take a closer look at <span class="bg-t-blue text-white">technological</span> developments.<br>What will it look like in the next few years?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'beralih ke kendaraan listrik atau bahan bakar gas',
                'titleen'=>'shift towards electric vehicles'
            ],
            [
                'id'=>'b',
                'title'=>'transportasi umum yang lebih baik',
                'titleen'=>'better public transportation'
            ],
            [
                'id'=>'c',
                'title'=>'digitalisasi dokumen penting seperti e-KTP',
                'titleen'=>'digitalization of essential documents (e-KTP)'
            ],
            [
                'id'=>'d',
                'title'=>'lebih banyak bisnis yang didukung teknologi canggih',
                'titleen'=>"more business supported by advanced technologies"
            ],
            [
                'id'=>'e',
                'title'=>'hilangnya kepercayaan terhadap teknologi',
                'titleen'=>'lost of trust towards technology'
            ],
            [
                'id'=>'f',
                'title'=>'kekhawatiran terhadap kerahasiaan data pribadi',
                'titleen'=>'data privacy concerns'
            ],
            [
                'id'=>'g',
                'title'=>'meningkatnya kesenjangan digital',
                'titleen'=>'increased digital gap'
            ],
            [
                'id'=>'h',
                'title'=>'akses internet dan komunikasi semakin mudah',
                'titleen'=>'better communication and access to internet'
            ],
            [
                'id'=>'i',
                'title'=>'kecanduan terhadap penggunaan teknologi',
                'titleen'=>'addiction towards technology and health decline'
            ],
            [
                'id'=>'j',
                'title'=>'lainnya',
                'titleen'=>'others'
            ],
        ]
    ],
    [
        'id'=>5,
        'title'=>'Mari perhatikan lagi, adakah hal yang berubah dalam <span class="bg-t-blue text-white">kehidupan sosial</span> di sekitar kita?',
        'titleen'=>'Going deeper, has antyhing shifted in our <span class="bg-t-blue text-white">social relationship</span> with others?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'meningkatnya kesadaran terhadap kesehatan mental',
                'titleen'=>'increased awareness towards mental health'
            ],
            [
                'id'=>'b',
                'title'=>'berkembangnya kebebasan berpendapat',
                'titleen'=>'increased freedom of speech'
            ],
            [
                'id'=>'c',
                'title'=>'menurunnya rasa kesatuan dalam masyarakat',
                'titleen'=>'lower social cohesion in society'
            ],
            [
                'id'=>'d',
                'title'=>'semangat gotong royong terus berkembang',
                'titleen'=>"continuity of community and collective sense"
            ],
            [
                'id'=>'e',
                'title'=>'terbatasnya ruang gerak untuk berpendapat',
                'titleen'=>'reduced freedom of speech and critical thinking'
            ],
            [
                'id'=>'f',
                'title'=>'cara pikir reaktif terhadap masalah yang dialami',
                'titleen'=>'reactive mindset towards challenges'
            ],
            [
                'id'=>'g',
                'title'=>'berkurangnya toleransi berakibat gerakan ekstrim',
                'titleen'=>'reduced tolerance that leads to radicalism'
            ],
            [
                'id'=>'h',
                'title'=>'banyaknya usaha berbasis isu sosial',
                'titleen'=>'proliferation of social-led businesses'
            ],
            [
                'id'=>'i',
                'title'=>'cara pikir preventif terhadap masalah yang dialami',
                'titleen'=>'preventive mindset towards challenges'
            ],
            [
                'id'=>'j',
                'title'=>'lainnya',
                'titleen'=>'others'
            ],
        ]
    ],
    [
        'id'=>6,
        'title'=>'Bagaimana dengan perubahan dalam roda <span class="bg-t-blue text-white">perekonomian</span> dan mata pencaharian?',
        'titleen'=>'What about <span class="bg-t-blue text-white">economic</span> changes and availability of jobs in the next decade?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'naiknya biaya hidup',
                'titleen'=>'increased living expenses'
            ],
            [
                'id'=>'b',
                'title'=>'turunnya nilai rupiah',
                'titleen'=>'lower currency value'
            ],
            [
                'id'=>'c',
                'title'=>'banyaknya lapangan kerja',
                'titleen'=>'increased employment opportunities'
            ],
            [
                'id'=>'d',
                'title'=>'tingginya angka pengangguran',
                'titleen'=>"growing unemployment"
            ],
            [
                'id'=>'e',
                'title'=>'kompetisi pasar yang membaik',
                'titleen'=>'better competitive market'
            ],
            [
                'id'=>'f',
                'title'=>'investasi pembangunan desa bertambah',
                'titleen'=>'increased investment towards rural areas'
            ],
            [
                'id'=>'g',
                'title'=>'bertambahnya bantuan langsung pemerintah',
                'titleen'=>'more direct assistance from government'
            ],
            [
                'id'=>'h',
                'title'=>'pembangunan ekonomi menelantarkan sektor lain',
                'titleen'=>'focus on development overcomes other targets'
            ],
            [
                'id'=>'i',
                'title'=>'berkurangnya investasi pihak asing',
                'titleen'=>'reduced foreign investment'
            ],
            [
                'id'=>'j',
                'title'=>'lainnya',
                'titleen'=>'others'
            ],
        ]
    ],
    [
        'id'=>7,
        'title'=>'Apabila terdapat berita Indonesia di tahun 2030, gambar mana yang kemungkinan besar akan ada di media tersebut?',
        'titleen'=>'Which image will likely represent the headlines in Indonesian newspaper in 2030?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'Teknologi',
                'titleen'=>'Technology',
                'img'=>'/images/img1.jpg',
                'color'=>'cyan',
            ],
            [
                'id'=>'b',
                'title'=>'Lingkungan',
                'titleen'=>'Environment',
                'img'=>'/images/img2.jpg',
                'color'=>'green',
            ],
            [
                'id'=>'c',
                'title'=>'Sosial',
                'titleen'=>'Social',
                'img'=>'/images/img3.jpg',
                'color'=>'yellow',
            ],
            [
                'id'=>'d',
                'title'=>'Ekonomi',
                'titleen'=>"Economy",
                'img'=>'/images/img4.jpg',
                'color'=>'pink',
            ],
        ]
    ],
    [
        'id'=>8,
        'title'=>'Apa yang menurut kamu dibutuhkan untuk masa depan yang lebih baik?',
        'titleen'=>'What do you think is needed to create a better future?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'meningkatkan partisipasi anak muda',
                'titleen'=>'increased youth participation'
            ],
            [
                'id'=>'b',
                'title'=>'aturan yang berdampak baik',
                'titleen'=>'better regulation to instill impact'
            ],
            [
                'id'=>'c',
                'title'=>'partisipasi masyarakat dalam pengambilan keputusan',
                'titleen'=>'involving communities in decision-making'
            ],
            [
                'id'=>'d',
                'title'=>'penelitian dengan data yang akurat',
                'titleen'=>"more research with reliable data"
            ],
            [
                'id'=>'e',
                'title'=>'produk inovatif pemecah masalah',
                'titleen'=>"innovative products to solve issues"
            ],
        ]
    ],
    [
        'id'=>9,
        'title'=>'Bagaimana kamu melihat keadaan kota di masa depan?',
        'titleen'=>'How do you see the future of cities?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'layanan dan jasa yang lebih mudah dijangkau',
                'titleen'=>'accesible products and services'
            ],
            [
                'id'=>'b',
                'title'=>'pemerintahan yang dapat beradaptasi',
                'titleen'=>'adaptive government'
            ],
            [
                'id'=>'c',
                'title'=>'berkurangnya kesenjangan di masyarakat',
                'titleen'=>'reduced level of inequality'
            ],
            [
                'id'=>'d',
                'title'=>'perubahan berbasis data',
                'titleen'=>"evidence-based interventions"
            ],
            [
                'id'=>'e',
                'title'=>'kota-kota yang terhubung dengan teknologi canggih',
                'titleen'=>"connected cities through smart technology"
            ],
        ]
    ],
    [
        'id'=>10,
        'title'=>'Apa yang membuat kamu bersemangat?',
        'titleen'=>'What are you passionate about?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'mempelajari tentang berbagai komunitas di Indonesia',
                'titleen'=>'learning about communities in Indonesia'
            ],
            [
                'id'=>'b',
                'title'=>'merencanakan sebuah intervensi terhadap masalah',
                'titleen'=>'planning interventions to solve challenges'
            ],
            [
                'id'=>'c',
                'title'=>'mengamati lingkungan sekitar untuk hal-hal baru',
                'titleen'=>'observing surrounding for new things'
            ],
            [
                'id'=>'d',
                'title'=>'melakukan penelitian tentang sebuah masalah',
                'titleen'=>"research on a certain issues"
            ],
            [
                'id'=>'e',
                'title'=>'merancang produk yang tepat guna',
                'titleen'=>"desgining effective products"
            ],
        ]
    ],
    [
        'id'=>11,
        'title'=>'Apabila bisa memilih, bagaimana kamu bisa membawa perubahan di masyarakat?',
        'titleen'=>'How would you go on to instill change in society?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'menggerakkan masyarakat dengan ide-ide baru',
                'titleen'=>"empower communities' with inventive ideas"
            ],
            [
                'id'=>'b',
                'title'=>'mengubah perilaku lebih baik melalui regulasi',
                'titleen'=>'influencing behavior through regulation'
            ],
            [
                'id'=>'c',
                'title'=>'mencari solusi dalam masyarakat',
                'titleen'=>'seek existing solution in communities'
            ],
            [
                'id'=>'d',
                'title'=>'menggunakan data secara kreatif',
                'titleen'=>"use data and conduct research"
            ],
            [
                'id'=>'e',
                'title'=>'mengembangkan produk atau jasa',
                'titleen'=>"mobilize resources and develop products"
            ],
        ]
    ],
    [
        'id'=>12,
        'title'=>'Sarana apa saja yang bisa kamu akses?',
        'titleen'=>'What resources do you have access to?',
        'option'=>[
            [
                'id'=>'a',
                'title'=>'kemampuan untuk melibatkan anak muda',
                'titleen'=>"youth engagement"
            ],
            [
                'id'=>'b',
                'title'=>'pengambilan keputusan dan kebijakan',
                'titleen'=>'policy and decision making'
            ],
            [
                'id'=>'c',
                'title'=>'inisiatif-inisiatif berbasis komunitas',
                'titleen'=>'community-based initiative'
            ],
            [
                'id'=>'d',
                'title'=>'advokasi, sumber pengetahuan dan pedoman',
                'titleen'=>"advocacy and source of knowledge"
            ],
            [
                'id'=>'e',
                'title'=>'pendanaan, wewenang dan pengaruh positif',
                'titleen'=>"funding and positive influence"
            ],
        ]
    ],
];

$config['text'] = [
    [
        'title'=>'Selamat datang, siapkah kamu untuk membangun masa depan Indonesia?',
        'titleen'=>'Welcome, are you ready to join us in developing the future of Indonesia?'
    ],
    [
        'title'=>'Dengan banyaknya hal yang tidak terduga, seperti pandemi, kami ingin mengetahui pendapat kamu tentang apa yang dibutuhkan untuk membangun Indonesia yang lebih tangguh ke depannya. Kami tahu kamu sibuk, maka kami janji survei ini hanya butuh beberapa menit saja.',
        'titleen'=>'With many uncertain events, such as the ongoing pandemic, we want your input to build a more resilient Indonesia moving forward through this quick survey. We are aware you are busy, but we promise it will just take a few minutes of your time.'
    ],
    [
        'title'=>'Pertama-tama,',
        'titleen'=>'Firstly,'
    ],
    [
        'title'=>'Kami ingin tahu sedikit tentangmu!',
        'titleen'=>'We want to know a little bit about you!'
    ],
    [
        'title'=>'Jangan khawatir,',
        'titleen'=>"Don't worry,"
    ],
    [
        'title'=>'Ini hanya pertanyaan mendasar. <br>Semua informasi yang kamu berikan akan kami jaga dengan baik.',
        'titleen'=>"It's just a couple of standard questions. <br>All the information you provide will be confidential."
    ],
    [
        'title'=>'Tentang Kamu',
        'titleen'=>'About You'
    ],
    [
        'title'=>'Kota: Sekarang & Masa Depan',
        'titleen'=>'Cities: Now & The Future'
    ],
    [
        'title'=>'Halo Inovator!',
        'titleen'=>'Hey Innovator!'
    ],
    [
        'title'=>'Hasil Akhir',
        'titleen'=>'Result'
    ],
    [
        'title'=>'Perkenalkan, kami dari UNDP Accelerator Lab Indonesia!',
        'titleen'=>'Let us introduce ourselves, we are UNDP Accelerator Lab Indonesia!'
    ],
    [
        'title'=>'Kamu adalah..',
        'titleen'=>'And you are...'
    ],
    [
        'title'=>'Nama',
        'titleen'=>'Name'
    ],
    [
        'title'=>'Jenis kelamin',
        'titleen'=>'Gender'
    ],
    [
        'title'=>'Laki-laki',
        'titleen'=>'Male'
    ],
    [
        'title'=>'Perempuan',
        'titleen'=>'Female'
    ],
    [
        'title'=>'Tidak Memilih',
        'titleen'=>'Prefer not to mention'
    ],
    [
        'title'=>'Umur',
        'titleen'=>'Age'
    ],
    [
        'title'=>'Pekerjaan',
        'titleen'=>'Occupation'
    ],
    [
        'title'=>'Pelajar/Mahasiswa',
        'titleen'=>'Student/Youth'
    ],
    [
        'title'=>'Karyawan Swasta',
        'titleen'=>'Private sector'
    ],
    [
        'title'=>'PNS',
        'titleen'=>'Government official'
    ],
    [
        'title'=>'Tidak Bekerja',
        'titleen'=>'Not Working'
    ],
    [
        'title'=>'Akademisi',
        'titleen'=>'Academia'
    ],
    [
        'title'=>'Wiraswasta',
        'titleen'=>'Entrepreneur'
    ],
    [
        'title'=>'Profesional',
        'titleen'=>'Professional'
    ],
    [
        'title'=>'Lainnya',
        'titleen'=>'Others'
    ],
    [
        'title'=>'Kota',
        'titleen'=>'City'
    ],
    [
        'title'=>'Untuk memahami lebih dalam mengenai kota tempat tinggalmu dan aspirasimu, penting bagi kami untuk mengenal kamu lebih lanjut.',
        'titleen'=>'To understand your city and aspirations better, it is important for us to get to know you better.'
    ],
    [
        'title'=>'Senang berkenalan denganmu,',
        'titleen'=>'Nice to meet you,'
    ],
    [
        'title'=>'Kami sangat senang untuk memulai perjalanan ini denganmu.',
        'titleen'=>'We are excited to start this journey together with you.'
    ],
    [
        'title'=>'Sejauh ini mudah kan?',
        'titleen'=>'So far, easy right?'
    ],
    [
        'title'=>'Sekarang mari kita mulai pertanyaan tentang <span class="text-t-yellow">kota</span>,',
        'titleen'=>"Now let's start with questions about cities,"
    ],
    [
        'title'=>'di masa ini dan ke depannya.',
        'titleen'=>"their conditions today and future outlook."
    ],
    [
        'title'=>'Pandemi dan berbagai bencana alam yang dialami oleh Indonesia membuat kita sadar akan betapa pentingnya untuk bertahan dan beradaptasi terhadap masalah yang akan datang.',
        'titleen'=>"The pandemic and recent natural disasters made us realize to importance of developing resilient cities and society in overcoming future challenges."
    ],
    [
        'title'=>'Mari pelajari kota kita lebih mendalam!',
        'titleen'=>"Let's go deeper to study our cities!"
    ],
    [
        'title'=>'Boleh pilih lebih dari satu, maksimal 3 jawaban',
        'titleen'=>"Can choose more than one, maximum 3 answers"
    ],
    [
        'title'=>'Wah, menarik sekali! Ternyata banyak hal yang kita sadari di sekitar kota ya, bagaimana dengan tanda-tanda perubahan lainnya?',
        'titleen'=>'It has been interesting learning about these challenges in your city. Now has there been any other signals of change that you notice?'
    ],
    [
        'title'=>'<span class="text-t-yellow">Tanda-tanda perubahan</span> adalah hal baru yang muncul di sekeliling kita, bisa dilihat dari obrolan umum, berita maupun perilaku yang berpotensi membawa transformasi di masa depan.',
        'titleen'=>'<span class="text-t-yellow">Signals of change</span> are anything new that recently came about in your surrounding, whether from informal discussions, news or even actions that has the potential to bring transformation to our future.'
    ],
    [
        'title'=>'Apakah akhir-akhir ini kamu sadari sesuatu dari diskusi dengan keluarga, tetangga dan teman kamu, mungkin dari berita atau media sosial?',
        'titleen'=>'Have you noticed something different in your discussions with family, friends or neighbors, perhaps something in the news or social media that caught your attention?'
    ],
    [
        'title'=>'Bagian tentang <span class="text-t-yellow">kota</span> sudah selesai!',
        'titleen'=>'We have concluded questions on <span class="text-t-yellow">cities!</span>'
    ],
    [
        'title'=>'Sekarang mari kita cari tahu tentang kekuatan kamu dalam menciptakan perubahan.',
        'titleen'=>"Now let's see what are your strengths in creating change in society."
    ],
    [
        'title'=>'Setelah membayangkan masa depan kita, inilah waktu untuk mencapainya! Bagaimana kita melakukannya?',
        'titleen'=>"Now that we have established our preferred future, it's time to achieve it! How do we do that?"
    ],
    [
        'title'=>'<span class="text-t-yellow">Bekerja sebagai satu tim</span>, mirip dengan semangat Pramuka dulu, namun sekarang dengan inovasi-inovasi untuk skala yang lebih besar.',
        'titleen'=>'<span class="text-t-yellow">Through collective action</span>, similar to the concept of scouts during our younger years, with innovation for a larger impact.'
    ],
    [
        'title'=>'Kamu tipe inovator yang mana?',
        'titleen'=>'Let’s see, which innovation scout are you?'
    ],
    [
        'title'=>'<span class="text-t-yellow">Selesai!</span> <span class="name">Nama</span>, kamu hebat sekali, kami belajar banyak mengenai apa saja yang membuat kamu antusias.',
        'titleen'=>'<span class="text-t-yellow">Done!</span> <span class="name">Nama</span>, You were amazing, we have gained a better understanding on what motivates you to drive change.'
    ],
    [
        'title'=>'Sekarang untuk momen yang ditunggu…',
        'titleen'=>"Now for the moment you've been waiting for…"
    ],
    [
        'title'=>'Terima kasih telah berpartisipasi, hasil analisa kami menunjukkan bahwa kamu adalah...',
        'titleen'=>'Thank you for participation, analysis of your response showcased that you are a...'
    ],
    [
        'title'=>'Selain kamu, terdapat inovator-inovator lainnya yang bersemangat untuk mencari solusi bersama. Sambil mengisi waktu luang, ada tantangan sedikit nih buat kamu!',
        'titleen'=>'Besides you, there are other innovators out there that are passionate to seek solutions together. In the next few weeks, we have a challenge for you!'
    ],
    [
        'title'=>'Lihat tantangan',
        'titleen'=>'Look at the challenges'
    ],
    [
        'title'=>'Mari kita lanjutkan perjalananmu sebagai bagian dari tim dengan berpartisipasi dalam acara peluncuran <span class="text-t-pink">Accelerator Lab Indonesia</span> pada <span class="text-t-green">Maret 2021</span> nanti, yang akan diisi dengan diskusi dan game yang interaktif, serta berbagai hadiah yang menarik.',
        'titleen'=>'Let\'s continue your journey as part of this team by participating in the <span class="text-t-pink">Accelerator Lab Indonesia</span> launch event in <span class="text-t-green">March 2021</span>, that will be filled with interactive discussion and games, as well as attractive doorprizes.'
    ],
    [
        'title'=>'Tunggu kabar selanjutnya di media sosial <a href="https://www.instagram.com/undpindonesia/?igshid=qp2dhqbig4o4" target="_blank"><span class="text-t-cyan">@UNDPIndonesia</span></a> ya. Sampai bertemu!',
        'titleen'=>'You can find more information on our social media <a href="https://www.instagram.com/undpindonesia/?igshid=qp2dhqbig4o4" target="_blank"><span class="text-t-cyan">@UNDPIndonesia</span></a>, looking forward to seeing you!'
    ],
    [
        'title'=>'Bagikan',
        'titleen'=>'Share'
    ],
];

$config['badge'] = [
    [
        'color'=>'yellow',
        'title'=>'Penjelajah Ide',
        'desc'=>'Kamu adalah sosok yang bersemangat untuk mengidentifikasi dan mengembangkan ide untuk berbagai isu, terutama mengikutsertakan pemuda dan profesional muda lainnya',
        'titleen'=>'Ideas Explorer',
        'descen'=>'Individuals that are passionate to identify and develop ideas to different complex development challenges, focusing on involvement from youth & young professionals',
        'og_title'=>'Penjelajah Ide',
        'og_desc'=>'Karakterku adalah seorang Penjelajah Ide, apa karaktermu? Yuk ikuti survei pendek ini untuk mengetahui kekuatanmu dalam membangun Indonesia yang lebih tangguh. Mari bersama membangun kembali!',
        'og_image_fb'=>$config['base_url'].'assets/images/badge/fb/a.jpg',
        'og_image_tw'=>$config['base_url'].'assets/images/badge/tw/a.jpg',
    ],
    [
        'color'=>'green',
        'title'=>'Pengantar Aksi',
        'desc'=>'Kamu adalah sosok yang kreatif dalam merencanakan dan melakukan aksi karena keterlibatanmu dalam proses pengambilan keputusan untuk memberikan dampak baik bagi masyarakat',
        'titleen'=>'Liaison to Action',
        'descen'=>'Individuals that has access to policy-making and/or a wide variety of resources (funding, etc) and can mobilize them to initiate actions in braoder society',
        'og_title'=>'Pengantar Aksi',
        'og_desc'=>'Karakterku adalah seorang Pengantar Aksi, apa karaktermu? Yuk ikuti survei pendek ini untuk mengetahui kekuatanmu dalam membangun Indonesia yang lebih tangguh. Mari bersama membangun kembali!',
        'og_image_fb'=>$config['base_url'].'assets/images/badge/fb/b.jpg',
        'og_image_tw'=>$config['base_url'].'assets/images/badge/tw/b.jpg',
    ],
    [
        'color'=>'blue',
        'title'=>'Pencari Solusi',
        'desc'=>'Kamu adalah sosok pemimpin di komunitas yang hobi untuk melihat sekeliling dalam mencari kearifan lokal atau solusi kreatif lainnya yang berpotensi untuk perubahan',
        'titleen'=>'Solution Seeker',
        'descen'=>'Individuals that possess close proximity to community-based solutions, adept at observing the value in driving systemic change',
        'og_title'=>'Pencari Solusi',
        'og_desc'=>'Karakterku adalah seorang Pencari Solusi, apa karaktermu? Yuk ikuti survei pendek ini untuk mengetahui kekuatanmu dalam membangun Indonesia yang lebih tangguh. Mari bersama membangun kembali!',
        'og_image_fb'=>$config['base_url'].'assets/images/badge/fb/c.jpg',
        'og_image_tw'=>$config['base_url'].'assets/images/badge/tw/c.jpg',
    ],
    [
        'color'=>'pink',
        'title'=>'Pemandu Pengembangan',
        'desc'=>'Kamu adalah sosok dengan antusiasme tinggi untuk mengembangkan penelitian dan menggunakan data secara inovatif dalam mengembangkan solusi-solusi di masyarakat',
        'titleen'=>'Growing Guide',
        'descen'=>'Individuals that have been actively trying to develop more research and utilize data to scale community-based solutions in different context and locations',
        'og_title'=>'Pemandu Pengembangan',
        'og_desc'=>'Karakterku adalah seorang Pemandu Pengembangan, apa karaktermu? Yuk ikuti survei pendek ini untuk mengetahui kekuatanmu dalam membangun Indonesia yang lebih tangguh. Mari bersama membangun kembali!',
        'og_image_fb'=>$config['base_url'].'assets/images/badge/fb/d.jpg',
        'og_image_tw'=>$config['base_url'].'assets/images/badge/tw/d.jpg',
    ],
    [
        'color'=>'red',
        'title'=>'Agen Perubahan',
        'desc'=>'Kamu adalah sosok yang memiliki pengaruh positif terhadap lingkungamu dan mampu menggunakan sumber daya berbeda untuk pengembangan produk dan servis yang baik untuk masyarakat',
        'titleen'=>'Change Agent',
        'descen'=>'Individuals that possess power to influence policy-makers and public, as well as mobilize different resources (R&D, funding) to deliver inventive products and services',
        'og_title'=>'Agen Perubahan',
        'og_desc'=>'Karakterku adalah seorang Agen Perubahan, apa karaktermu? Yuk ikuti survei pendek ini untuk mengetahui kekuatanmu dalam membangun Indonesia yang lebih tangguh. Mari bersama membangun kembali!',
        'og_image_fb'=>$config['base_url'].'assets/images/badge/fb/e.jpg',
        'og_image_tw'=>$config['base_url'].'assets/images/badge/tw/e.jpg',
    ],
];
$config['task'] = [
    [
        'title'=>'Melihat berbagai isu di perkotaan, apa ide transformatif yang ingin kamu coba dan tes dalam rangka mencari solusi?',
        'titleen'=>'Seeing many issues in the city, what transformative ideas would you try and test in order to seek for appropriate solutions?',
    ],
    [
        'title'=>'Coba pikirkan contoh dimana perubahan yang didasarkan peraturan telah berhasil dalam menjawab kebutuhan masyarakat?',
        'titleen'=>'Think of an example, where regulation-led social innovation has successfully accommodate an need/gap from the community?',
    ],
    [
        'title'=>'Lihat di area sekeliling tempat tinggalmu, apa solusi yang telah dikembangkan masyarakat setempat untuk isu yang mereka hadapi?',
        'titleen'=>'Try and have a look at your surrounding neighborhoods, what local wisdom to a challenge that your community has come up with?',
    ],
    [
        'title'=>'Melihat berbagai isu di perkotaan, apa sumber data baru yang dapat kamu gunakan untuk mengembangkan penelitian untuk isu ini?',
        'titleen'=>'If you encounter a challenge in the city, what kind of new data would use to develop knowledge around it?',
    ],
    [
        'title'=>'Coba pikirkan contoh dimana kerjasama yang dimulai oleh sebuah bisnis berhasil dalam mengikutsertakan masyarakat dalam prosesnya dan memberikan dampak positif?',
        'titleen'=>'Think of an example, where buisness-led social partnership that deliver change and involved citizens in the process?',
    ],

];
$config['validation'] = [
    [
        'title'=>'Harus diisi.',
        'titleen'=>'This field is required.',
    ],
    [
        'title'=>'Silakan isi alamat email dengan benar.',
        'titleen'=>'Please enter a valid email address.',
    ],
    [
        'title'=>'Harap masukkan tidak lebih dari {0} karakter.',
        'titleen'=>'Please enter no more than {0} characters.',
    ],
    [
        'title'=>'Harap masukkan nilai yang lebih besar dari atau sama dengan {0}.',
        'titleen'=>'Please enter a value greater than or equal to {0}.',
    ],
];